repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: file-contents-sorter
        files: ^(\.cspell\/custom-dictionary-workspace.txt|requirements\.txt)$
        args: ["--ignore-case", "--unique"]
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: (example_chart.yml|solaredge.yaml)
    -   id: check-json
        exclude: ^(\.cspell\.json|\.devcontainer\/devcontainer\.json)$
-   repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
    -   id: check-json5
        files: ^(\.cspell\.json|\.devcontainer\/devcontainer\.json)$
# -   repo: https://github.com/PyCQA/isort
#     rev: 5.12.0
#     hooks:
#     -   id: isort
# -   repo: https://github.com/pylint-dev/pylint
#     rev: v3.0.2
#     hooks:
#     -   id: pylint

# -   repo: https://github.com/psf/black
#     rev: 22.10.0
#     hooks:
#     -   id: black
# - repo: https://github.com/igorshubovych/markdownlint-cli
#   rev: master  # or specific git tag
#   hooks:
#     - id: markdownlint # Configure in .mdlrc
# - repo: https://github.com/streetsidesoftware/cspell-cli
#   rev: v8.0.0
#   hooks:
#     - id: cspell
#       additional_dependencies:
#         - "@cspell/dict-en-gb"
      # args:
        # - "lint"
        # - "--locale"
        # - "en-GB" # We do this for this doc's simplicity
